CREATE TABLE IF NOT EXISTS t_genx (
	'id' INT(11) NOT NULL AUTO_INCREMENT,
	'montant' DECIMAL(12,2) DEFAULT NULL,
	'designation' TEXT DEFAULT NULL,
	'numeroCheque' TEXT DEFAULT NULL,
	'idProjet' INT(12) DEFAULT NULL,
	'dateLivraison' DATE DEFAULT NULL,
	'status' VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY ('id')
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;